### ISSUE TITLE
Timezone Warning (Eventually will raise an exception)

### ISSUE THREAD

**Issue by WizRd0** [travisghansen/hass-opnsense#136]
Home Assistant Logs

> This error originated from a custom integration.
> 
> Logger: py.warnings
> Source: custom_components/opnsense/pyopnsense/__init__.py:301
> integration: OPNsense (documentation, issues)
> First occurred: 7:44:52 AM (2 occurrences)
> Last logged: 7:45:25 AM
> 
> /usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname ACST identified but not understood. Pass `tzinfos` argument in order to correctly return a timezone-aware datetime. In a future version, this will raise an exception. warnings.warn("tzname {tzname} identified but not understood. "

**Comment by madansu** [comment]
I am having the same issue
I am using the dockerized version of home assistant (2024.5.2), and keep getting these errors in my logs 
[py.warnings] /usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname PDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

**Comment by alexdelprete** [comment]
please test v0.2.0 and in case create another issue.
