### ISSUE TITLE
API permission error due to fetching data for disabled entities.

### ISSUE THREAD

**Issue by mkopnsrc** [travisghansen/hass-opnsense#184]
If the entities are not enabled in HA, The OPNsense plugin should not try to fetch data for those entities from OPNsense firewall. This will  reduce overall calls within OPNsense by homeassistant plugin. In my case here, I do not use OpenVPN in OPNsense so I have not given API permissions. Ideally, the plugin should fetch data for only enabled entities.

![image](https://github.com/user-attachments/assets/ebd3b6d6-0974-465f-b096-d3deba3160e0)

**Comment by alexdelprete** [comment]
1. Data is collected, then entities are updated. Please read HA documentation to understand how it works: https://developers.home-assistant.io/docs/integration_fetching_data#polling-api-endpoints

![image](https://github.com/user-attachments/assets/d0f8d8c0-3064-4bfa-9f99-8aefdbe3665f)

2. You ask this just because you don't want to give an API permission for OpenVPN, question is: why bother, since your openvpn is not active?
3. The official recommendation (check README) is to use an admin role user. If you don't want to, we provide the possible (unsupported) granular privileges needed, but you don't want to follow that recommendation either, so you ask for an ideal code change. That's not how it works, unfortunately.
4. You can submit a PR and devs will evaluate it.

**Comment by mkopnsrc** [comment]
Thanks for the info, didn't know HA was limiting API pull calls. I'm sure there could be alternative way, will open up a PR when I find something.

**Comment by alexdelprete** [comment]
> didn't know HA was limiting API pull calls

Limiting? What are you referring to?
