### ISSUE TITLE
Upgraded, Now I Have Two Routers?

### ISSUE THREAD

**Issue by wormuths** [travisghansen/hass-opnsense#215]
I upgraded the plugin, and it created a duplicate device.  Now I have my OPNSense router twice, with a ton of unavailable entities.

**Comment by alexdelprete** [comment]
Yes, happened to me too, sorry about that.

Delete both instances and readd the integration. Many changes are happening, @Snuffy2 is doing a hard work and this project is getting all the love it deserves.

**Comment by alexdelprete** [comment]
> It left me with only 22 entities being provided. So many things were missing that I restored to before the re-install and I'm back where I was.

Many entities are disabled by default, you need to enable them. I only enable what's needed for my use-case, and it makes sense to have most of them disabled.

**Comment by Snuffy2** [comment]
I've also had the issue a couple of times where the integration has created a second instance. This has happened in versions before and after v0.2.0 to me. I suspect it has to do with the way the device id is created and used. I'd like to improve this but I'm still brainstorming how best to do it without breaking existing installs.

Totally agree that with all of these updates that we don't rename the entities when possible. It was unavoidable for the Service switches and OpenVPN sensors. The rest should have maintained their same names with all of the updates from v0.2.0+

It is interesting that you noted on reinstall you ended up with only 22 entities. I had the same issue last night (see #220). At least in my case it was because of a bad URL for OPNsense, but I can't reproduce it. Either way, I'll improve the validation in config_flow to try to prevent that from happening again. If you have logs from the reinstall with 22 entities, please pass it along.

**Comment by alexdelprete** [comment]
Weird. This afternoon a second device with only sensors was created. Obviously all duplicated sensors.
I agree it's something related to how the device_id is created. I have an idea: since device_id has to be unique, if OPNsense API doesn't provide a unique sn for the device, we could use the MAC address or something related to a hw unique s/n (CPU?). Just brainstorming...I'll think about it...

I must also say that this didn't happen until last week.

![image](https://github.com/user-attachments/assets/d119e82c-b042-44d2-a22e-2afef80a7412)

**Comment by c3p0vsr2d2** [comment]
I removed the integration, rebooted, and then readded it.
I see some switches which were provided by the integration are missing (I did check disabled switches as well).
For example, Wireguard VPN service switch is missing, even though there are sensor entities indicating state.
What gives?

**Comment by oblivioncth** [comment]
Just wanted to note that this still happened to me after updating to 0.3.5, as the above PR implies it was resolved, in case more work should be done.

I'll just reinstall the integration.

**Comment by Snuffy2** [comment]
Glad you got everything working. 

I should have clarified with v0.3.5 better. It unfortunately wasn't going to remove duplicate devices but should prevent it from happening going forward.

**Comment by alexdelprete** [comment]
> Thanks for all the hard work @alexdelprete and @Snuffy2 ... IT IS greatly appreciated.

99.9% of credit goes to the devs: @travisghansen and @Snuffy2. I'm just helping them, and the only credit I take was convincing Travis to create an integration also for OPNsense (he made one for pfSense). Now I simply help and brainstorm with them. :)

**Comment by alexdelprete** [comment]
> I was using the pfSense integration @alexdelprete made

You meant @travisghansen. Luckily I managed to convince him to do it also for OPNsense. :)
