### ISSUE TITLE
[Bug]: High Load

### ISSUE THREAD

**Issue by o0shojo0o** [travisghansen/hass-opnsense#246]
### What happened?

I have noticed that my OPNsense is now consuming a lot more CPU power. 
The increased consumption started with the current beta phase.
![image](https://github.com/user-attachments/assets/c165dbf7-65e1-47f6-b9c7-e777ce0e03bb)

### hass-opnsense Version

v0.3.5-beta.3

### OPNsense Firmware

24.7.5_3

### Home Assistant Version

2024.10.0

### Additional Details

OPNsense System:

- Intel Celeron J3160 CPU (4 cores, 1.6 GHz) 
- 4GB Ram

**Comment by alexdelprete** [comment]
Can you disable the integration for 1h to check if it actually lowers cpu usage?

**Comment by o0shojo0o** [comment]
With active integration:
![image](https://github.com/user-attachments/assets/96a37813-835a-4f0b-ab5f-611671f7a9ca)

 with stopped integration:
 
![image](https://github.com/user-attachments/assets/c30be8b1-78d4-42e8-9797-51e862d956da)

**Comment by Snuffy2** [comment]
I just put out a Pre-release testing version without concurrency. Please give it a try and see what it does for your OPNsense load.

Release Tag: InSeries-1

<img width="1152" alt="2024-10-10_19-30-09 206" src="https://github.com/user-attachments/assets/1f0b7c60-138c-44e1-8b9b-641938129774">

<img width="1152" alt="2024-10-10_19-30-35 523" src="https://github.com/user-attachments/assets/432e443a-c589-4549-8500-a9a72a71814c">

**Comment by Snuffy2** [comment]
Sorry, had to change release to v0.3.6-alpha.1

<img width="1152" alt="2024-10-10_20-27-51 707" src="https://github.com/user-attachments/assets/2e75bbfb-783f-43d3-95de-0caab14389ba">

**Comment by alexdelprete** [comment]
> With active integration: ![image](https://private-user-images.githubusercontent.com/19333515/375366203-96a37813-835a-4f0b-ab5f-611671f7a9ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzIzMDIsIm5iZiI6MTcyODYzMjAwMiwicGF0aCI6Ii8xOTMzMzUxNS8zNzUzNjYyMDMtOTZhMzc4MTMtODM1YS00ZjBiLWFiNWYtNjExNjcxZjdhOWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjg1M2Y2MTlhNTFmMDAxMjcxYzM1ODM5NDJhODE0NDQzYjNjYzMxYmQyYWY3YjZkY2E0ZTdjOTJiZmNiODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S8nSDRshezHYH2WMMk6liPEawE2atAV1QVkej6SVu5E)
> 
> with stopped integration: ![image](https://private-user-images.githubusercontent.com/19333515/375366326-c30be8b1-78d4-42e8-9797-51e862d956da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzIzMDIsIm5iZiI6MTcyODYzMjAwMiwicGF0aCI6Ii8xOTMzMzUxNS8zNzUzNjYzMjYtYzMwYmU4YjEtNzhkNC00MmU4LTk3OTctNTFlODYyZDk1NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTI0ODE5OGIxZDZmOGI5ZTgxN2RlOGQxMzNlYzNiMzBhYmJmMmE2NWFjZDgxYTY4YjU5YWIzZGVlZmRlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OEipX1LEJDiHyIzthgxnzDmjbYhTqnOzaBz6LdD2-pI)

Please test latest alpha so we can see if the load is the same with/without the integration. Thank you.

**Comment by o0shojo0o** [comment]
It has already improved a lot. Unfortunately, I can’t assess how much the API calls should strain the small system. 
We’re probably already at the optimal point here.

Thank you all for your effort and time.

With active integration: 
![image](https://github.com/user-attachments/assets/887a1d3b-4795-4839-8457-cffca7c1b935)

With stopped integration: 
![image](https://github.com/user-attachments/assets/0e6770a7-f92e-48fa-8844-62c0274cc778)

**Comment by Snuffy2** [comment]
I only setup concurrency (using asyncio.gather) for the setup of the sensors and switches (only on load) and then on the coordinator. This alpha version removed it for the coordinator. Since sensors and switches is just a load time, I'll leave those.

Other than that, the rest of the REST API queries should be happening in series. We are now using async for the integration but that shouldn't affect this. We are also now using aiohttp for the REST API queries (instead of requests which was used previously). This is what allowed the parallel queries to work. But with the changes in this alpha release, the queries remain asynchronous in the sense that they don't block the event loop, but should be happening in series.

I'll take the PR from this alpha version, add some additional logging in the integration to count the number of XMLRPC and REST API queries being done with each coordinator update and reinstate the method timing that was there previously but was removed as it was not compatible with asyncio.gather. I may also need to update the timing method itself as I'm not sure how accurate it is with async methods but I'll look into it.

I'll also see if I can find anything else that could be causing increased stress on OPNsense, but nothing else is coming to mind right now.

As an FYI, I can't easily test this locally as I'm running 2+ versions of this integration for dev purposes so my load is not normal anyway. Also, not as extreme as @alexdelprete and his MS-01, I'm not seeing much of a hit on my hardware even when running 2+ versions of the OPNsense integration. I forget what I'm using, but I think it's an Intel Celeron N5105.
