### ISSUE TITLE
[FR]: Show Wireguard client state (online/offline)

### ISSUE THREAD

**Issue by davidgdlt** [travisghansen/hass-opnsense#285]
### Describe the new feature or enhancement idea

Currently for each client we have a switch where (among other things) we can track its state, understanding state as whether wireguard (and possibly other VPN servers) accepts connections for that particular client / with its associated credentials.

What we don't have (that I can see) is whether there is an active connection associated with the client, ie. what we see in the wireguard widget represented as a green/red coloured network icon.

We could also track the number of active connections associated withe a server, which is also available in the widget at the top, eg. Tunnels: 4 | **Online: 1** | Offline: 3

This would be great to have to, for example, trigger HA automations (eg. notifications) based on new active connections to the VPN.

Thanks in advance

### Will you be building this?

- [ ] I intend to submit a PR to implement this

**Comment by Snuffy2** [comment]
Wireguard is stateless so there isn't exactly a great definition of connected or not. However, I never even enabled the OPNsense Wireguard Widget since they went to the new version. That's a great pointer/suggestion.

Looking at their code, it looks like they count a Wireguard client as `online` if the last handshake was <3 min ago. I could duplicate that logic if that sounds good.

https://github.com/opnsense/core/blob/8e41be2ebe8b53d59fded39d289c5d73822c8083/src/opnsense/www/js/widgets/Wireguard.js#L89

Now to see how they are counting OpenVPN clients and may replicate that as well ....
