### ISSUE TITLE
Only devices with static DHCP showing up

### ISSUE THREAD

**Issue by gotschi** [travisghansen/hass-opnsense#34]
Hi, thank you for this great plugin!

One problem I have is that only the devices with static leases show up as `device_tracker` entities.
All others (dynamic leases) do not show up.

Is this intended? Is this a bug only I observe? Can I change sth about this?

I'm monitoring wifi devices across APs and SSIDs in HA with the help of openwrt and display the device entities according to where they are connected. I would love to also see devices with dynamic leases in there (as I don't set leases in a guest network e.g.)

**Comment by travisghansen** [comment]
Welcome!

You must explicitly select which entities you want to follow for device tracker and that process is not connected to dhcp at all, it strictly reads the arp table of opnsense.

Can you provide more detail and explain what leads you to believe the static entries are relevant?

**Comment by gotschi** [comment]
I just figured it's opnsense which only puts clients with a static dhcp lease in the arp table (in contrast to openwrt where any dhcp lease is added to the arp table I think). Not a issue where I cannot see devices provided by the integration but being deactivated - I activated them all.

So this is not a bug or issue at all, it's just wrong assumption on my side.
Having devices with dynamic dhcp leases show up as device tracker entities would be nice though, so maybe you are able to join the arp table with dhcp lease table and result even more devices this way, just a suggestion.

**Comment by travisghansen** [comment]
Any device that has recently communicated with the router will have an entry in the arp table (regardless of dhcp or not). I don’t automatically add all devices in the arp table as device tracker entities on purpose as the number could be huge and generally folks want to track very specific devices.

So yeah, this integration you have to manually pick the specific devices you want to track (in the configuration screen), otherwise the devices are ignored.
